### PR TITLE
Bug/255/function pointers and file leak

### LINKED ISSUE #255: Problem with real-world projects. Example: VIM
linked branch: `bug/function_pointers`

## Test-case: VIM (https://github.com/vim/vim)
- Creation of monolithic `vim.ll` using `gllvm` successful.
- Compilation of `vim.ll` into executable successful.

## Problem:
- `DiscoPoP`optimizer pass not successful
  - ## Error 1 
  - `could not find the FileMapping file`
  - STILL WIP, arises at first LLVM Module
  - Only arises, if `runOnFunction` was executed prio
    - maybe unclosed files? 

  - ## Error 2
  - `LLVM ERROR: Broken function found, compilation aborted!`
-  UPDATE: The problem seems to arise from called `Function Pointers`
  - Example: 
  - `(*mb_char2bytes)(curr_c, buf);`
  - Results: no function can be determined @`DiscoPoP.cpp:570` 
  ```
CallInst* ci = cast<CallInst>(instruction);
Function *f = ci->getCalledFunction();
```
- origin:  Lines 14883-14886 in `vim.ll`
```
  %39 = load i32 (i32, i8*)*, i32 (i32, i8*)** @mb_char2bytes, align 8, !dbg !128487
  %40 = load i32, i32* %curr_c, align 4, !dbg !128488
  %arraydecay = getelementptr inbounds [22 x i8], [22 x i8]* %buf, i64 0, i64 0, !dbg !128489
  %call40 = call i32 %39(i32 %40, i8* %arraydecay), !dbg !128490
```
or line `389` in `vim/src/arabic.c`:
```
// Update the first byte of the character.
(*mb_char2bytes)(curr_c, buf);
```
- UPDATE: FIXED

## Potential solutions:
- NEW
- If function*, create a placeholder in CU.
- If funciton*, get address at runtime, check against known function* (@function_name are just pointers internally) and store the called function at runtime. Fill in the gathered information into the Data.xml
- fill the placeholder after runtime (post or pre-processing)

## Tested:
- Check why FileMapping is not found in the second module.

### PR DESCRIPTION
**Pull request by lukasrothenberger**
- Fixes #255
- Fixed open file leak
  - One file handle has been left open per analyzed function
  - Problem only occurred if the target project was large enough (e.g. VIM)  
- Adds `DP_VERBOSE` flag to `DiscoPoP.cpp` (not yet fully supported)
- Pretty printing of `runOnModule` progress
- Moved contents of  `DPReductionUtils.cpp` to `DiscoPoP.cpp` and removed `DPReductionUtils`

### CODE REVIEW

File: DiscoPoP/DiscoPoP.cpp [hunk 1]
```diff
@@ -1015,6 +1022,129 @@ void DiscoPoP::instrument_loop(Function &F, int file_id, llvm::Loop *loop, LoopI
...
+    std::ifstream fmap_file;
+    fmap_file.open(fmap_path.c_str());
+    if(fmap_file.fail()) {
+        std::cout << "Opening FileMapping failed: " << strerror(errno) << "\n";
+    }
+    if (!fmap_file.is_open()) {
+        std::cout << "FMAP FILE IS NOT OPEN!\n";
+        return false;
+    }
+    std::cout << "AFTER OPENING\n";
```
Comment (lukasrothenberger) [inline DiscoPoP/DiscoPoP.cpp:1035]:
```suggestion
        return false;
    }
```

**Review by goerlibe — APPROVED** [review]
